//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YDock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHide.
        /// </summary>
        public static string _AutoHide {
            get {
                return ResourceManager.GetString("_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close(_C).
        /// </summary>
        public static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHide(_A).
        /// </summary>
        public static string AutoHide {
            get {
                return ResourceManager.GetString("AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        public static string Close_All {
            get {
                return ResourceManager.GetString("Close_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all except this(_A).
        /// </summary>
        public static string Close_All_Except {
            get {
                return ResourceManager.GetString("Close_All_Except", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDock(_K).
        /// </summary>
        public static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document(_T).
        /// </summary>
        public static string Dock_Document {
            get {
                return ResourceManager.GetString("Dock_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToFloat(_F).
        /// </summary>
        public static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float all.
        /// </summary>
        public static string Float_All {
            get {
                return ResourceManager.GetString("Float_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide(_H).
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window position.
        /// </summary>
        public static string Window_Position {
            get {
                return ResourceManager.GetString("Window_Position", resourceCulture);
            }
        }
    }
}
